config/routes.rb
require './app/store'
Depot::Application.routes.draw do
  
  match 'catalog' => StoreApp.new, via: :all
  get 'admin' => 'admin#index'
    get 'contact' => 'contact#index'
    get 'about' => 'about#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"
  
  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
     
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all

  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  #...

  #before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
#
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  validates :title, length: {minimum: 2}
  validates :description , length:{minimum: 5}

  paginates_per 5

  def self.latest
    Product.order(:updated_at).last
  end

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end     
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	skip_before_action :authorize 
  def index
  
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
skip_before_action :authorize 
  def index
  	user = User.find_by(name: params[:name])
    
    
  
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  # ...
  private
  # ...

    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  include CurrentCart
  before_action :set_cart
  def index
    if params[:set_locale]
      redirect_to store_url(locale: params[:set_locale])
    else
      @products = Product.order(:title).page(params[:page])
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
	<% if session[:user_id] %>
	


 <h1>Welcome </h1>

 <tr>
  		<%@total_orders = Order.count%>	

 
  <h3>We have <%= pluralize(@total_orders, "order") %></h3>
  
  
  <%= link_to 'check', orders_path ,class: 'pedi'%>

 <h3>Today <%=  Time.now.strftime("%Y-%m-%d %H:%M")  %></h3>
 <%else%>
 <h1>welcome</h1>
 please login to manage your store.

 <%= button_to 'Login', login_url, class: 'subb',data: { confirm: 'Are you a manager?' }  %>
 <%end%>



  

  

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Musical Instrument  Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START:i18n -->
  <div id="banner">
<!-- START_HIGHLIGHT -->
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale',
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
<!-- END_HIGHLIGHT -->
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
<!-- END:i18n -->
  <div id="columns">
    <div id="side">
      <!-- START:hidden_div -->
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
    <!-- END:hidden_div -->

      <ul>

      <li><a href="http://localhost:3000"><%= t('.home') %></a></li>
        <li><a href="http://localhost:3000/about"><%= t('.about') %></a></li>

        <li><a href="http://localhost:3000/contact"><%= t('.contact') %></a></li>

        <li><%= link_to t('.admin_html'),  admin_path  %></li>
      </ul>


      <% if session[:user_id] %>
        <ul>
          <li><%= link_to t('.order_html'),   orders_path   %></li>
          <li><%= link_to t('.product_html'), products_path %></li>
          <% user = User.find_by(id: session[:user_id]) %>
          <% if user.admin %>
            <li><%= link_to t('.users_html'),    users_path    %></li>
          <% end %>
        </ul>
        <%= button_to t('.logout_html'), logout_path, class: 'ord',method: :delete,data: { confirm: 'Are you sure to logout?' }  %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

Thank you for your recent order from The Pragmatic Store.

You ordered the following items:

<%= render @order.line_items -%>

We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Order Shipped</h3>
<p>
  This is just to let you know that we've shipped your recent order:
</p>

<table>
  <tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/app/views/order_notifier/shipped.text.erb