config/routes.rb
require './app/store'
Depot::Application.routes.draw do
  
  match 'catalog' => StoreApp.new, via: :all
  get 'admin' => 'admin#index'
    get 'contact' => 'contact#index'
    get 'about' => 'about#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"
  
  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
     
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all

  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create, :show]
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.order('created_at desc').page(params[:page])
    @order_total_price = {}
    @order_products = {}

    @orders.each do |order|
      total_price = 0
      products = []

      order.line_items.each do |li|
        total_price += li.total_price.to_i
        products << li.product
      end

      @order_total_price["#{order.id}"] = total_price
      @order_products["#{order.id}"] = products
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @total_price = 0
    @order_products = []

    @order.line_items.each do |li|
      @total_price += li.total_price.to_i
      @order_products << li.product
    end
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end

    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderNotifier.received(@order).deliver
        format.html { redirect_to order_path(@order.id), notice:
          I18n.t('.thanks') }
        format.json { render action: 'show', status: :created,
          location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
  #...
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<!-- START:explanation -->
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
<!-- START_HIGHLIGHT -->
      <h2><%=raw t('errors.template.header', count: @order.errors.count,
        model: t('activerecord.models.order')) %>.</h2>
      <p><%= t('errors.template.body') %></p>
<!-- END_HIGHLIGHT -->

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
<!-- START_HIGHLIGHT -->
        <li><%=raw msg %></li>
<!-- END_HIGHLIGHT -->
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- ... -->
<!-- END:explanation -->

  <div class="field">
<!-- START_HIGHLIGHT -->
    <%= f.label :name, t('.name') %><br>
<!-- END_HIGHLIGHT -->
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
<!-- START_HIGHLIGHT -->
    <%= f.label :address, t('.address_html') %><br>
<!-- END_HIGHLIGHT -->
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>
  <div class="field">
<!-- START_HIGHLIGHT -->
    <%= f.label :email, t('.email') %><br>
<!-- END_HIGHLIGHT -->
    <%= f.email_field :email, size: 40 %>
  </div>
  <div class="field">
<!-- START_HIGHLIGHT -->
    <%= f.label :pay_type, t('.pay_type') %><br>
<!-- END_HIGHLIGHT -->
    <%= f.select :pay_type, Order::PAYMENT_TYPES,
#START_HIGHLIGHT
                  prompt: t('.pay_prompt_html') %>
<!-- END_HIGHLIGHT -->
  </div>
  
  <div class="actions">
<!-- START_HIGHLIGHT -->
    <%= f.submit t('.submit') %>
<!-- END_HIGHLIGHT -->
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Name &nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Address&nbsp;</th>
      <th>Email&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;Pay type</th>
      <th>&nbsp;&nbsp;Total</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>

        <td>&nbsp;&nbsp;&nbsp;&nbsp;<%= order.address %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= order.email %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= order.pay_type %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;<%= @order_total_price["#{order.id}"] %></td>



        <td><%= link_to 'Show', order,class: 'sho' %></td>
        <td><%= link_to 'Edit', edit_order_path(order),class: 'edi'%></td>
        <td><%= link_to 'Destroy', order, class: 'des',method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path,class: 'ord' %>
<!-- START_HIGHLIGHT -->
<p><%= paginate @orders %></p>
<!-- END_HIGHLIGHT -->

app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
<!-- START_HIGHLIGHT -->
    <legend><%= t('.legend') %></legend>
<!-- END_HIGHLIGHT -->
    <%= render 'form' %>
  </fieldset>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= @total_price %>
</p>

<p>
  <strong>Product:</strong>
  <% @order_products.each do |p| %>
    <td><%=link_to "#{p.title}",  product_path(id: p.id) %><%= image_tag p.image_url %></td>
  <% end %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>